# shellcheck shell=bash
# Chapter 1 — variables. Run from this directory: `just run`

set shell := ['zsh', '-cu']

default:
    @just --list

run:
    @cargo run

watch:
    @cargo-watch -qc -x run -x clippy

clippy:
    @cargo clippy
